### ISSUE TITLE
[검색창] Top Sheet Fragment 관련

### ISSUE THREAD

**Issue by Int-TRUE** [GDSC-KNU/4CutAlbum-client#1]
@Glacier-Han 
원래는 아래 Figma디자인처럼 위에서 내려오는 Top Sheet Fragment로 구현하려고 했으나
안드로이드에서는 Bottom sheet 형태만 지원을 하고있었습니다..
그래서 커스텀하고자 이리저리 해봤지만 잘 안돼서 우선은 Bottom sheet로 구현하고 이슈로 남깁니다!
(대부분의 기존 앱들이 bottom sheet로만 구현하는 이유가 여기있을지도...)

사실 bottom으로 해놓고보니 나쁘지않아서 굳이 top으로 할 필요는 없을 것 같다는 생각이 들지만
일단은 이슈로 남깁니다..!
따라서 별로 중요하지 않은 부분이라 시간 여유로우실 때 한번 봐주시면 좋을 것 같습니다!

![image](https://user-images.githubusercontent.com/87708291/232856700-cacfcd84-9352-4e63-b7f4-30c5666cb5a1.png)

**Comment by Glacier-Han** [comment]
확인을 좀 해보았는데, 구현하신 bottomSheetBehavior로 저렇게 커스텀 하는건 힘들 것 같고
https://github.com/MedveDomg/AndroidTopSheet
여기 TopSheet로 커스텀한 라이브러리를 찾았는데
6년 전이 마지막 업데이트라 영,,좀 그렇네요 ㅋㅋㅋㅋㅋ
글고 바텀시트 해놓으신거 넘 이뻐서 바텀시트로 해도 무난할 것 같아요.

수고하셨습니다~~

**Comment by Glacier-Han** [comment]
그리고 바텀시트랑 스피너 칩 다 너무 깔끔하게 잘 구현하셨네요 ㅋㅋㅋ.... 한수 배워갑니닷🫡
