### ISSUE TITLE
CreateFeedResponse의 반환값으로 null이 날아옵니다.

### ISSUE THREAD

**Issue by Int-TRUE** [GDSC-KNU/4CutAlbum-client#3]
### CreateFeedResponse
@sami355-24 
response 자체는 성공(code 200)인데 saveFeedId에 null이 담겨옵니다.
![image](https://github.com/GDSC-KNU/4CutAlbum-client/assets/87708291/07bd7046-c082-4ac4-af43-cae93ca28d42)

전체 피드리스트를 불러올 때 나타나는 것으로 봐서, 서버에도 정상적으로 잘 등록된 것으로 보이고, feed list를 받아왔을 때 로그를 보면 feed id 자체는 정상적으로 등록된 것 처럼 보입니다.
![image](https://github.com/GDSC-KNU/4CutAlbum-client/assets/87708291/7e270e5a-53f7-4650-91c6-e31da485e87d)

테스트한 인자값은 아래와 같습니다. 이미지 base 64문자열만 달라지고, 나머지 인자는 거의 동일하게 주고 테스트 하고 있는데, 모두 id가 잘 안담기는 것 같습니다.
![image](https://github.com/GDSC-KNU/4CutAlbum-client/assets/87708291/250819fc-a8e2-4a2f-ad29-76eb72f2ca4b)

**Comment by sami355-24** [comment]
항상 null이 넘어오는건가요 아니면 특정경우에만 null이 넘어 온다는 말씀이신가요??

아마도 feed id의 타입문제는 아닐듯합니다.

**Comment by Int-TRUE** [comment]
항상 null이 넘어오는 것 같습니다!

**Comment by sami355-24** [comment]
저의 local 환경에서 postman으로 save요청을 했을때는 정상동작하였습니다.
혹시 코멘트를 공백으로해서 보내셨나요?
만약 공백으로 할 경우 서버에서 처리하는데 오류가 발생할수있습니다.

**Comment by Int-TRUE** [comment]
comment에 postman 예시와 동일하게 testComment를 넣어도 오류가 납니다..!

**Comment by sami355-24** [comment]
오늘 한번 보고 내일중으로 말씀드릴게요
Postman으로 똑같이 요청을보내도 오류가 날까요?

**Comment by Int-TRUE** [comment]
아니요, 저도 포스트맨으로는 요청이 잘됩니다!

**Comment by Int-TRUE** [comment]
원래는 Model을 만들어서 그 안에 받아오도록 했는데, 바로 String으로 받아오도록 하니까 id 받아와졌습니다..!!
@sami355-24 
그냥 바로 String값 전달 받는것으로 해결하겠습니다!!

**Comment by sami355-24** [comment]
@Int-TRUE 
피드 생성 로직에서 반환값으로는 다음과 값이 반환합니다.
<img width="663" alt="Snipaste_2023-05-16_19-52-53" src="https://github.com/GDSC-KNU/4CutAlbum-client/assets/72246411/3c7d8f56-a5a8-47d9-b9a3-80966ca9d84f">

서버에서 FeedId를 Long타입으로 반환합니다.
아마도 서버에서 반환하는 타입이랑 클라이언트가 매핑하는 타입이 서로 달라서 생긴 문제였을수도 있을것 같네요.
